spring:
  application:
    name: DistributedNotificationProcessing
logging:
  level:
    root: warn
#  file:
#    name: logs/application.log
#    max-size: 20MB

#server:
#  tomcat:
#    max-connections: 5000
#    accept-count: 2000
#    threads:
#      max: 300
#      min-spare: 50